### ISSUE TITLE
Header authentication

### ISSUE THREAD

**Issue by caiodangelo** [caiodangelo/quotes-springboot#2]
Implement an interceptor that requires a pre-determined header in order to proceed with the requests

**Comment by krishnadwypayan** [comment]
Hi!
I'd like to work on this.
Could you elaborate on what the header would be?

**Comment by caiodangelo** [comment]
Awesome! I was thinking in a sort of x-api-key or something like this.

Every request should come with this header. For now we can define the authorized key via an environment variable.

Later on I can create another issue to evolve this feature with a endpoint to manage this tokens.

**Comment by krishnadwypayan** [comment]
Could you give an example, maybe?

**Comment by caiodangelo** [comment]
`curl -i -X GET \
 'http://q4u.herokuapp.com/quotes/random'`

Today this endpoint is open to the world. I want that it only accept requests that comes with the x-api-key header, like this:

`curl -i -X GET \
   -H "x-api-key:533515a53e116707135e11687c0a2b0d" \
 'http://q4u.herokuapp.com/quotes/random'`

**Comment by shubhammishra13** [comment]
what you need is an authentication service to validate requests , am i right?

**Comment by shubhammishra13** [comment]
I would like to contribute to this .

**Comment by caiodangelo** [comment]
Exactly @shubhammishra13. Be my guest.

**Comment by caiodangelo** [comment]
Solved by PR #4
